defaults:
  - _self_

general:
  problem_type: 'classification'
  stop_criteria: 'val_loss'
  batch_size: 256
  iters: 300
  stop_patience: 20
  weight_lr: 0.001
  device: 'cpu'
  seed: 123
  dataset: 'higgs_large'

search_space:
  layer_widths: [512, 512, 512, 512, 512]
  activation: 'relu'

tabgns:
  temperature: 1.0
  arch_lr: 0.05
  gate_initialisation_val: -3
  scale: true
